### ISSUE TITLE
rshim should exit when cuse is missing

### ISSUE THREAD

**Issue by mgerdts** [Mellanox/rshim-user-space#26]
rshim has no chance of doing anything useful when the `cuse` kernel module cannot be loaded.  It should log an appropriate message and exit non-zero immediately.  This would make debugging this failure mode much easier.

This is with rshim built from commit 9b1da8407833cab4966c5f110df7683b646c2489.

```
# ./rshim -b pcie -d 0000:d8:00.2 -l 4 -f
modprobe: FATAL: Module cuse not found in directory /lib/modules/4.18.0-80.el8.27782638.x86_64
```

At this point it just keeps running.

**Comment by hselasky** [comment]
Which OS are you using? cuse.ko is only for FreeBSD ?

**Comment by mgerdts** [comment]
I'm using CentOS 8 with an in-house kernel.  I have subsequently found that the `cuse` module comes from `kernel-modules-extra`, which our internal build process has inconveniently not propagated beyond build servers.  That's something that I need to rectify.

That finding suggest that the `rshim` rpm could benefit from a dependency on `kernel-modules-extra` to head off this problem.

**Comment by lsun100** [comment]
The rshim.spec file does have check for kernel-modules-extra:
%if 0%{?rhel} >= 8 || 0%{?fedora} > 0
Requires: kernel-modules-extra
%endif

Probably the check failed. I'll take to take a look.

**Comment by lsun100** [comment]
Mike, the RPM does check the kernel-modules-extra (see below). Probably the RPM binary you used was built in a slightly different way. The source RPM in the release tarball should be good. 

# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

#rpmbuild --rebuild rshim-2.0.5-2.g9b1da84.src.rpm

# rpm -ivh rshim-2.0.5-2.g9b1da84.el8.x86_64.rpm
error: Failed dependencies:
        kernel-modules-extra is needed by rshim-2.0.5-2.g9b1da84.el8.x86_64

**Comment by mgerdts** [comment]
Hmm, the version I have is indeed busted and different.

```
[root@xxx ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

[root@xxx ~]# rpm -q kernel-modules-extra
package kernel-modules-extra is not installed

[root@xxx ~]# rpm -ivh rshim-2.0.5-OFED.5.1.0.6.6.x86_64.rpm
warning: rshim-2.0.5-OFED.5.1.0.6.6.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 6224c050: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:rshim-2.0.5-OFED.5.1.0.6.6       ################################# [100%]
Created symlink /etc/systemd/system/multi-user.target.wants/rshim.service → /usr/lib/systemd/system/rshim.service.

[root@xxx ~]# rpm -q --requires --recommends --suggests -p rshim-2.0.5-OFED.5.1.0.6.6.x86_64.rpm
warning: rshim-2.0.5-OFED.5.1.0.6.6.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 6224c050: NOKEY
/bin/sh
/bin/sh
config(rshim) = 2.0.5-OFED.5.1.0.6.6
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
libc.so.6(GLIBC_2.9)(64bit)
libfuse.so.2()(64bit)
libfuse.so.2(FUSE_2.4)(64bit)
libfuse.so.2(FUSE_2.5)(64bit)
libfuse.so.2(FUSE_2.8)(64bit)
libpci.so.3()(64bit)
libpci.so.3(LIBPCI_3.0)(64bit)
libpci.so.3(LIBPCI_3.5)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libusb-1.0.so.0()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
[root@xxx ~]#
```

That doesn't look like what you get with `rshim.spec.in` or `rhel/rshim.spec.in`.  It looks like I was provided with a goofy build and this can be closed.
