### ISSUE TITLE
rshim needs to respect SIGTERM and SIGINT

### ISSUE THREAD

**Issue by mgerdts** [Mellanox/rshim-user-space#27]
I needed to make a modification to `/etc/rshim.conf`.  After doing so, it seemed prudent to restart `rshim.service`.  That took a very long time because `rshim` seems to ignore `SIGTERM`.  Or perhaps it just ignores `SIGTERM` in the bad state that caused me to want to modify the configuration.  `journalctl` tells me:

```
Aug 12 16:39:30 xxx systemd[1]: Stopping rshim driver for BlueField SoC...
Aug 12 16:41:00 xxx systemd[1]: rshim.service: State 'stop-sigterm' timed out. Killing.
Aug 12 16:41:00 xxx systemd[1]: rshim.service: Killing process 31084 (rshim) with signal SIGKILL.
Aug 12 16:41:00 xxx systemd[1]: rshim.service: Failed with result 'timeout'.
Aug 12 16:41:00 xxx systemd[1]: Stopped rshim driver for BlueField SoC.
Aug 12 16:41:00 xxx systemd[1]: Starting rshim driver for BlueField SoC...
Aug 12 16:41:00 xxx systemd[1]: Started rshim driver for BlueField SoC.
```

I observed similar problems with `SIGINT` when trying to use `^C` to kill an `rshim` instance that was running in the foreground.

Note that this happened when I was debugging problems on a machine where the running kernel is missing `cuse.ko` (see #26), in case that matters.  It was observed with the 2.0.5 build and with bits I built from commit  9b1da8407833cab4966c5f110df7683b646c2489.

**Comment by lsun100** [comment]
Mike, just wondering if you still see the issue with latest code? I'll mark the issue as close for now.
We can reopen it if problem still exists.
