### ISSUE TITLE
Lsun, rshim and Fedora

### ISSUE THREAD

**Issue by pypingou** [Mellanox/rshim-user-space#34]
Sorry for opening a ticket for this.

The Fedora Infrastructure has been trying to contact @lsun100 since September 5th without any success.
We raised the issue in the Fedora devel list (cf: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/3NZNSFKSS25EVEA6RY42LVOPZ74NGUQU/ ), also without success.

@lsun100 if you see this, feel free to close it and reach out by email (either to me or to the address (admin@...) that is sending you the daily notifications).

Thanks!

**Comment by lsun100** [comment]
Really sorry for it. Somehow I didn't see the notice, or probably it's hidden somewhere.
I'll try to solve it soon and will contact you if I need help.

**Comment by lsun100** [comment]
I used to have account in redhat bugzilla using email (lsun@mellanox.com), but somehow couldn't login any more.
I'm trying to figure out what happened...

**Comment by lsun100** [comment]
I created the redhat bugzilla again using email address lsun@mellanox.com. @pypingou Could you help check whether this is what we needed?

**Comment by pypingou** [comment]
On Fri, Oct 02, 2020 at 08:19:48PM -0700, Liming Sun wrote:
>    I created the redhat bugzilla again using email address
>    [1]lsun@mellanox.com. [2]@pypingou Could you help check whether this is
>    what we needed?

Looks all good for me, thank you very much !

**Comment by lsun100** [comment]
Thanks!!
