### ISSUE TITLE
add tags for revisions

### ISSUE THREAD

**Issue by mbgg** [Mellanox/rshim-user-space#41]
Hi,

Would it be possible to add git tags for the new revisions?
git tag rshim-2.0.5-4 9fc3c34
git tag rshim-2.0.5-5 4d8571f

That would make integration in Open Build Service (https://build.opensuse.org/package/show/hardware/rshim) easier, as we could use a service file to download and check new software versions.

**Comment by lsun100** [comment]
Sure, will do and update it here. Thanks!

**Comment by lsun100** [comment]
Sorry for the delay. Somehow it doesn't seem trigger email (or might be filtered). I'll try to watch more closely.

**Comment by lsun100** [comment]
Done. I'll add tag when bumping up the version next time. Thanks!

**Comment by mbgg** [comment]
Thanks a lot!
